name: wf_dev_pr
on: 
  pull_request:
    branches:
      - develop
jobs:
  dev_pr_job:
    runs-on: ubuntu-latest
    steps: 
      - name:  Welcome Step
        run: echo "Welcome to the Github Actions"